### Database-Style	DataFrame	Joins

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({'key': 'b b a c a a b'.split(),
                    'data1': range(7)})

In [3]:
df2 = pd.DataFrame({'key': 'a b d'.split(),
                    'data2': range(3)})

In [4]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [5]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [6]:
pd.merge(df1, df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [7]:
# use key to specify

pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [14]:
# change columns name
df1.columns = ['data', 'lkey']

In [17]:
# change columns name

df2.rename(columns={'key': 'rkey'}, inplace=True)

In [18]:
df2

data2 rkey
0      0    a
1      1    b
2      2    d

In [20]:
pd.merge(df1, df2, left_on='lkey', right_on='rkey')

data lkey  data2 rkey
0     0    b      1    b
1     1    b      1    b
2     6    b      1    b
3     2    a      0    a
4     4    a      0    a
5     5    a      0    a

In [22]:
# find back missing data 
df3 = df1.rename(columns={'lkey': 'key'})

In [23]:
df4 = df2.rename(columns={'rkey': 'key'})

In [24]:
pd.merge(df3, df4, how='outer')

data key  data2
0   0.0   b    1.0
1   1.0   b    1.0
2   6.0   b    1.0
3   2.0   a    0.0
4   4.0   a    0.0
5   5.0   a    0.0
6   3.0   c    NaN
7   NaN   d    2.0

In [25]:
# many-to-many merges

In [28]:

df1 = pd.DataFrame(['b b a c a b'.split(), list(range(6))])
# df1 = pd.DataFrame({'key': })

In [33]:
df1 = df1.T

In [35]:
df1.columns = ['key', 'data1']

In [36]:
df1

key data1
0   b     0
1   b     1
2   a     2
3   c     3
4   a     4
5   b     5

In [42]:
df2 = pd.DataFrame(['a b a b d'.split(), list(range(5))])

In [43]:
df2 = df2.T

In [44]:
df2.columns = ['key', 'data2']

In [45]:
df2

key data2
0   a     0
1   b     1
2   a     2
3   b     3
4   d     4

In [46]:
# merge
pd.merge(df1, df2, on='key', how='left')

key data1 data2
0    b     0     1
1    b     0     3
2    b     1     1
3    b     1     3
4    a     2     0
5    a     2     2
6    c     3   NaN
7    a     4     0
8    a     4     2
9    b     5     1
10   b     5     3

In [47]:
# inner kw

pd.merge(df1, df2, how='inner')

key data1 data2
0   b     0     1
1   b     0     3
2   b     1     1
3   b     1     3
4   b     5     1
5   b     5     3
6   a     2     0
7   a     2     2
8   a     4     0
9   a     4     2

In [48]:
# multiple keys

left = pd.DataFrame({'key1': 'foo foo bar'.split(),
                     'key2': 'one two one'.split(),
                     'lval': range(1,4)})

In [49]:
right = pd.DataFrame({'key1': 'foo foo bar bar'.split(),
                      'key2': 'one one one two'.split(),
                      'rval': range(4, 8)})

In [50]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [51]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [52]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [53]:
# overlapping names

pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [54]:
# suffix

pd.merge(left, right, on='key1', suffixes=['_left', '_right'])

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

### Merging	on	Index

In [55]:
left1 = pd.DataFrame({'key': 'a b a a b c'.split(),
                      'value': range(6)})

In [56]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index='a b'.split())

In [57]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [58]:
right1

group_val
a        3.5
b        7.0

In [59]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [60]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [62]:
# 

lefth = pd.DataFrame({
    'key1': 'Ohio Ohio Ohio Nevada Nevada'.split(),
    'key2': [2000, 2001, 2002, 2001, 2002],
    'data': np.arange(5.0)
})

In [63]:
righth = pd.DataFrame(np.arange(12).reshape((6,2)),
                     index=['Nevada Nevada Ohio Ohio Ohio Ohio'.split(),
                           [2001, 2000, 2000, 2000, 2001, 2002]],
                     columns=['event1', 'event2'])

In [64]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [65]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [66]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [67]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True, how='outer')

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

In [68]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                    index='a c e'.split(),
                    columns='Ohio Nevada'.split())

In [69]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                     index='b c d e'.split(),
                     columns='Missouri Alabama'.split())

In [70]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [71]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [72]:
pd.merge(left2, right2, how='outer', right_index=True, left_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [74]:
# a convenient way -- join 

left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [77]:
left2.join?

In [78]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                      index='a c e f'.split(),
                      columns=['new york', 'oregon'])

In [79]:
another

new york  oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [80]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [81]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

### Concatenating	Along	an	Axis

In [82]:
arr = np.arange(12).reshape((3,4))

In [83]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [85]:
arr2 = np.arange(8).reshape(2,4)

In [86]:
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
np.concatenate([arr, arr2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [88]:
arr3 = np.arange(8).reshape(4,2)

In [89]:
np.concatenate([arr, arr3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [90]:
np.concatenate([arr,arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
s1 = pd.Series([0, 1], index='a b'.split())

In [92]:
s2 = pd.Series([2, 3, 4], index='c d e'.split())

In [93]:
s3 = pd.Series([5, 6], index='f g'.split())

In [94]:
s1

a    0
b    1
dtype: int64

In [95]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [96]:
# change the axis

pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [97]:
pd.concat?

In [98]:
s4 = pd.concat([s1, s3])

In [99]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [100]:
pd.concat([s1, s4], axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [101]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [102]:
# join_axes

pd.concat([s1, s4], axis=1, join_axes=['a c b e'.split()])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [103]:
result = pd.concat([s1, s2, s3], keys='one two three'.split())

In [104]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [105]:
s1

a    0
b    1
dtype: int64

In [106]:
s2

c    2
d    3
e    4
dtype: int64

In [107]:
s3

f    5
g    6
dtype: int64

In [108]:
result = pd.concat([s1, s2, s3], axis=1, keys='one two three'.split())

In [109]:
result

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [110]:
# the same logic extends to dataframe

In [111]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2), index='a b c'.split(), columns=['one', 'two'])

In [112]:
df2 = pd.DataFrame(5+np.arange(4).reshape(2, 2), index='a c'.split(), columns='three four'.split())

In [113]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [114]:
df2

three  four
a      5     6
c      7     8

In [115]:
pd.concat([df1, df2])

four  one  three  two
a   NaN  0.0    NaN  1.0
b   NaN  2.0    NaN  3.0
c   NaN  4.0    NaN  5.0
a   6.0  NaN    5.0  NaN
c   8.0  NaN    7.0  NaN

In [116]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [117]:
# same as 

pd.concat({'level1': df1, 'level2': df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [118]:
# 

df1 = pd.DataFrame(np.random.randn(3,4), columns='a b c d'.split())

In [119]:
df2 = pd.DataFrame(np.random.randn(2,3), columns='b d a'.split())

In [120]:
pd.concat([df1, df2], ignore_index=True)

a         b         c         d
0 -0.172046  0.353593 -2.120594 -1.320042
1 -0.623692 -0.625164 -0.827019 -0.891829
2  0.642205  0.333876 -0.002022 -2.307376
3  0.951992 -1.243597       NaN -0.968995
4 -0.566199  0.390382       NaN -0.442848

### Combining	Data	with	Overlap

In [121]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
             index='f e d c b a'.split())

In [122]:
b = pd.Series(np.arange(len(a), dtype=np.float64),
             index='f e d c b a'.split())

In [123]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [124]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [125]:
b[-1] = np.nan

In [126]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [127]:
np.where(pd.isnull(a), b, a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [128]:
np.where?

In [130]:
b[:2].combine_first(a[2:])

a    NaN
b    4.5
c    3.5
d    NaN
e    1.0
f    0.0
dtype: float64

In [131]:
# combine_first

In [132]:
df1 = pd.DataFrame({
    'a': [1, np.nan, 5., np.nan],
    'b': [np.nan, 2., np.nan, 6.],
    'c': range(2, 18, 4)
})

In [133]:
df2 = pd.DataFrame({
    'a': [5, 4, np.nan, 3, 7],
    'b': [np.nan, 3., 4., 6., 8.]
})

In [ ]:
df1.combine_first(d)