### Array

关于 array 数据结构

- [官方文档](https://docs.python.org/2/library/array.html)

In [1]:
from array import array
from random import random

In [2]:
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.4352318662972241

In [3]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)

In [4]:
fp.close()

In [7]:
fp = open('floats.bin', 'rb')
floats2 = array('d')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.4352318662972241

In [8]:
floats2[0]

0.45597977007647106

In [9]:
numbers = array('h', [-1, 0, 1, 3, 6])
memv = memoryview(numbers)
len(memv)

5

In [10]:
memv[-1]

6

In [11]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[255, 255, 0, 0, 1, 0, 3, 0, 6, 0]

In [12]:
memv_oct[4]

1

In [13]:
numbers

array('h', [-1, 0, 1, 3, 6])

#### 关于 memoryview

memoryview 可以在不复制原有 bytes/array/list 的情况下进行切片，所以速度飞快

In [19]:
# 展现 memoryview 速度的时候到了

import time

lst = [100000, 200000, 300000, 400000]
def bytes_f():
    for i in lst:
        b = b'*' * i
        start = time.time()
        data = b
        while data:
            data = data[1:]
        print('bytes: ', time.time()-start)
        
def mv_f():
    
    for i in lst:
        b = b'^' * i
        start = time.time()
        data = memoryview(b)
        while data:
            data = data[1:]
        print('memoryview: ', time.time()-start)
        
bytes_f()
mv_f()

bytes:  0.19703364372253418
bytes:  0.7462060451507568
bytes:  1.761091947555542
bytes:  3.1140663623809814
memoryview:  0.007876873016357422
memoryview:  0.017180681228637695
memoryview:  0.025109052658081055
memoryview:  0.03312110900878906


注意： memoryview 接受 bytes 类型, 处理 list 类型时结合 array 

In [25]:
lst = [10000, 20000, 30000, 40000]
def bytes_f():
    for i in lst:
        b = [i for i in range(i)]
        start = time.time()
        data = array('d', b)
        while data:
            data = data[1:]
        print('bytes: ', time.time()-start)
        
def mv_f():
    
    for i in lst:
        b = [i for i in range(i)]
        start = time.time()
        data = memoryview(array('d', b))
        while data:
            data = data[1:]
        print('memoryview: ', time.time()-start)
bytes_f()
mv_f()

bytes:  0.0161745548248291
bytes:  0.0697031021118164
bytes:  0.15073466300964355
bytes:  0.26092982292175293
memoryview:  0.0015418529510498047
memoryview:  0.0028285980224609375
memoryview:  0.004189252853393555
memoryview:  0.006185770034790039


#### 简单 numpy/scipy


In [26]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
type(a)

numpy.ndarray

In [28]:
a.shape # 检测 a 的维数， 结果显示 1 维 12 个元素

(12,)

In [29]:
a.shape = 3,4  # 修改为 3 维 4 元素
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a[0] # 第 0 行

array([0, 1, 2, 3])

In [31]:
a[2,1]

9

In [32]:
a[:, 1] # 第 1 列

array([1, 5, 9])

In [33]:
a.transpose() # 转置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [36]:
# 读取文件
# pass

#### deque and queue

In [37]:
from collections import deque
dp = deque(range(10), maxlen=10)
dp

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
dp.rotate(3)
dp

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [39]:
dp.rotate(-3)
dp

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
dp.appendleft(-1)
dp

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
dp.extend([10, 11, 12])
dp

deque([2, 3, 4, 5, 6, 7, 8, 10, 11, 12])

In [42]:
dp.extendleft([-10, -8, -6, -4])
dp

deque([-4, -6, -8, -10, 2, 3, 4, 5, 6, 7])

In [46]:
# 非固定长度

dp2 = deque(range(10))
dp2

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
dp2.append(10)
dp2

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [48]:
dp2.sort(reverse=True)
dp2

AttributeError: 'collections.deque' object has no attribute 'sort'

In [52]:
sdp = sorted(dp2, reverse=True)
sdp

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]