### Indexing	with	slices

In [1]:
import numpy as np

In [2]:
arr = np.array(list(range(10)))

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [5]:
# 2d 数组
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# multiple slice

arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr2d[2, 1:]

array([8, 9])

In [11]:
arr2d[:2, 1]

array([2, 5])

In [12]:
# assign value using mutiple slice

arr2d[:2, 1:] = 0

In [13]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean	Indexing

In [20]:
names = np.array(['bob', 'joe', 'will', 'bob', 'joe', 'will'])

In [22]:
data = np.random.randn(6,4)

In [16]:
names

array(['bob', 'joe', 'will', 'bob', 'joe', 'will'],
      dtype='<U4')

In [23]:
data

array([[-1.14199769,  0.7956313 , -0.28605587,  0.849226  ],
       [-0.13682574, -0.30717051,  0.05007623, -0.35008983],
       [ 0.53752005, -0.75647637, -1.23196977,  0.82442934],
       [ 0.02118064,  0.89150654,  1.88974653, -2.20581971],
       [ 0.17838251, -0.60490386, -0.50101683, -0.8409568 ],
       [ 1.54942109, -0.77555495,  0.40499589, -0.76732332]])

In [21]:
names == 'bob'

array([ True, False, False,  True, False, False], dtype=bool)

In [24]:
data[names=='bob']

array([[-1.14199769,  0.7956313 , -0.28605587,  0.849226  ],
       [ 0.02118064,  0.89150654,  1.88974653, -2.20581971]])

In [25]:
data[names=='bob', 2:]

array([[-0.28605587,  0.849226  ],
       [ 1.88974653, -2.20581971]])

In [26]:
data[names=='bob', 3]

array([ 0.849226  , -2.20581971])

In [27]:
data[names != 'bob']

array([[-0.13682574, -0.30717051,  0.05007623, -0.35008983],
       [ 0.53752005, -0.75647637, -1.23196977,  0.82442934],
       [ 0.17838251, -0.60490386, -0.50101683, -0.8409568 ],
       [ 1.54942109, -0.77555495,  0.40499589, -0.76732332]])

In [28]:
data[~(names=='bob')]

array([[-0.13682574, -0.30717051,  0.05007623, -0.35008983],
       [ 0.53752005, -0.75647637, -1.23196977,  0.82442934],
       [ 0.17838251, -0.60490386, -0.50101683, -0.8409568 ],
       [ 1.54942109, -0.77555495,  0.40499589, -0.76732332]])

In [29]:
cond = names == 'bob'

In [30]:
data[cond]

array([[-1.14199769,  0.7956313 , -0.28605587,  0.849226  ],
       [ 0.02118064,  0.89150654,  1.88974653, -2.20581971]])

In [31]:
data[~cond]

array([[-0.13682574, -0.30717051,  0.05007623, -0.35008983],
       [ 0.53752005, -0.75647637, -1.23196977,  0.82442934],
       [ 0.17838251, -0.60490386, -0.50101683, -0.8409568 ],
       [ 1.54942109, -0.77555495,  0.40499589, -0.76732332]])

In [33]:
cond2 = (names=='bob') | (names=='will')

In [34]:
data[cond2]

array([[-1.14199769,  0.7956313 , -0.28605587,  0.849226  ],
       [ 0.53752005, -0.75647637, -1.23196977,  0.82442934],
       [ 0.02118064,  0.89150654,  1.88974653, -2.20581971],
       [ 1.54942109, -0.77555495,  0.40499589, -0.76732332]])

In [35]:
data[cond2, :2]

array([[-1.14199769,  0.7956313 ],
       [ 0.53752005, -0.75647637],
       [ 0.02118064,  0.89150654],
       [ 1.54942109, -0.77555495]])

In [36]:
# caution 

# 1. 'and' or 'or'  operator will not work in boolean slice
# 2. boolean slice will make a copy from raw data

In [37]:
# condtions assignment

data[data<0] = 0

In [38]:
data

array([[ 0.        ,  0.7956313 ,  0.        ,  0.849226  ],
       [ 0.        ,  0.        ,  0.05007623,  0.        ],
       [ 0.53752005,  0.        ,  0.        ,  0.82442934],
       [ 0.02118064,  0.89150654,  1.88974653,  0.        ],
       [ 0.17838251,  0.        ,  0.        ,  0.        ],
       [ 1.54942109,  0.        ,  0.40499589,  0.        ]])

In [39]:
data[data>0] = 1

In [40]:
data

array([[ 0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.]])

In [41]:
data[cond] = 7

In [42]:
data

array([[ 7.,  7.,  7.,  7.],
       [ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  1.],
       [ 7.,  7.,  7.,  7.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.]])

### fancy indexing

In [46]:
arr = np.zeros((8,4))

In [47]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [54]:
for i in range(10,18):
    arr[i-10] = i

In [55]:
arr

array([[ 10.,  10.,  10.,  10.],
       [ 11.,  11.,  11.,  11.],
       [ 12.,  12.,  12.,  12.],
       [ 13.,  13.,  13.,  13.],
       [ 14.,  14.,  14.,  14.],
       [ 15.,  15.,  15.,  15.],
       [ 16.,  16.,  16.,  16.],
       [ 17.,  17.,  17.,  17.]])

In [56]:
arr[[4,3,0,6]]

array([[ 14.,  14.,  14.,  14.],
       [ 13.,  13.,  13.,  13.],
       [ 10.,  10.,  10.,  10.],
       [ 16.,  16.,  16.,  16.]])

In [57]:
arr[[-3,-5,-7]]

array([[ 15.,  15.,  15.,  15.],
       [ 13.,  13.,  13.,  13.],
       [ 11.,  11.,  11.,  11.]])

In [58]:
arr = np.arange(32).reshape(8,4)

In [59]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
arr.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [61]:
arr.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr[[1,5,7,2],[0,1,2,3]]

array([ 4, 21, 30, 11])

In [64]:
arr[[1,5,7,2]][:,[0,1,2,3]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

### Transposing	Arrays	and	Swapping	Axes

In [65]:
arr = np.arange(15).reshape(3,5)

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
arr = np.random.randn(6,3)

In [69]:
arr

array([[-0.03814382,  0.25819616, -1.44335144],
       [ 1.14429328,  0.873277  ,  0.10918806],
       [-0.16279269,  0.20256267, -0.99218952],
       [ 1.48183651, -1.10782037, -1.06915746],
       [-1.24735806,  0.95962688, -0.60128961],
       [ 1.4063484 ,  0.17146624,  1.20299132]])

In [70]:
np.dot(arr.T, arr)

array([[ 7.06692091, -1.64100501,  1.1990511 ],
       [-1.64100501,  3.04786001,  0.3353962 ],
       [ 1.1990511 ,  0.3353962 ,  6.03146042]])

In [71]:
np.dot?

In [72]:
arr = np.arange(16).reshape((2,2,4))

In [73]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [75]:
arr.transpose?

In [76]:
arr 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
swaparr = arr.swapaxes(1,2)

In [80]:
swaparr

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [81]:
id(swaparr)

139690044268992

In [82]:
id(arr)

139690044218304