## 4.4	File	Input	and	Output	with	Arrays

In [1]:
import numpy as np

In [2]:
# save

arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('4-4-arr', arr)

In [5]:
ls

４.1 NumPy basics Arrays and Vectorized Computation.ipynb
４.2-1 Universal?Functions Fast?Element-Wise?Array Functions.ipynb
4.1-2 Indexing?with?slices.ipynb
4.3-1 Array-Oriented?Programming?with?Arrays.ipynb
4-4-arr.npy
4.4?File?Input?and?Output?with?Arrays.ipynb


In [6]:
# load 

In [7]:
np.load('4-4-arr.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# savez

np.savez('4-4-arr-savez',a=arr, b=arr)

In [11]:
arch = np.load('4-4-arr-savez.npz')

In [14]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# savez_compressed

np.savez_compressed('4-4-arr-comp', a=arr, b=arr)

In [18]:
arch = np.load('4-4-arr-comp.npz')

In [19]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])