## 4.5	Linear	Algebra

In [1]:
import numpy as np

In [2]:
x = np.array(list(range(1,7))).reshape(2,3)

In [3]:
y = np.array(list(range(7,13))).reshape(3,2)

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
x.dot(y)

array([[ 58,  64],
       [139, 154]])

In [7]:
y.dot(x)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [8]:
np.dot(x,y)

array([[ 58,  64],
       [139, 154]])

In [9]:
np.dot(y,x)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [10]:
# ones 

np.dot(x, np.ones(3))

array([  6.,  15.])

In [11]:
x @ np.ones(3)

array([  6.,  15.])

In [12]:
# numpy.linalg

In [13]:
from numpy.linalg import inv, qr

In [14]:
x = np.random.randn(5,5)

In [15]:
mat = x.T.dot(x)

In [16]:
mat

array([[  9.24278988,   7.58478486,   2.07582508,   2.21519386,
         -2.83655179],
       [  7.58478486,  12.64056334,   3.31763779,   1.98960882,
         -4.56943588],
       [  2.07582508,   3.31763779,   3.12112048,   0.33920863,
         -1.29937517],
       [  2.21519386,   1.98960882,   0.33920863,   1.46545043,
         -1.39278657],
       [ -2.83655179,  -4.56943588,  -1.29937517,  -1.39278657,
          2.28872649]])

In [17]:
inv(mat)

array([[ 0.39586387, -0.39505908, -0.13065162, -0.91458882, -0.92885772],
       [-0.39505908,  0.79512724,  0.10201068,  1.40523783,  2.01091039],
       [-0.13065162,  0.10201068,  0.53210641,  0.62284897,  0.7228617 ],
       [-0.91458882,  1.40523783,  0.62284897,  4.5966018 ,  4.82288529],
       [-0.92885772,  2.01091039,  0.7228617 ,  4.82288529,  6.64583188]])

In [18]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,  -4.44089210e-16,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
         -8.88178420e-16,   0.00000000e+00],
       [  2.22044605e-16,  -4.44089210e-16,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   8.88178420e-16,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00]])

In [19]:
q, r = qr(mat)

In [20]:
q

array([[-0.7302042 ,  0.64893502, -0.00427711,  0.18391494, -0.10882168],
       [-0.59921754, -0.69589272,  0.22870776,  0.22104579,  0.23559114],
       [-0.16399553, -0.16329331, -0.96800153, -0.04734713,  0.08468792],
       [-0.17500602,  0.12264016,  0.0970823 , -0.79097786,  0.56503216],
       [ 0.2240949 ,  0.23002467, -0.03496465,  0.53798358,  0.77860213]])

In [21]:
r

array([[ -1.26578152e+01,  -1.50291476e+01,  -4.36615964e+00,
         -3.43396007e+00,   5.77907784e+00],
       [  0.00000000e+00,  -5.22326853e+00,  -1.72859023e+00,
         -1.43080101e-01,   1.90693061e+00],
       [  0.00000000e+00,   0.00000000e+00,  -2.19299509e+00,
          3.08177457e-01,   9.62452479e-03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -1.07729379e+00,   8.62743453e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.17156459e-01]])