## 4.1	The	NumPy ndarray: A Multidimensional Array Object


In [1]:
import numpy as np

In [2]:
np.arange?

In [3]:
my_arr = np.arange(100000)

In [4]:
my_list = list(range(100000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 4.25 ms


In [7]:
%time for _ in range(10): my_list2 = my_list*2

CPU times: user 20 ms, sys: 4 ms, total: 24 ms
Wall time: 27.4 ms


In [8]:
# generate some random data

data = np.random.randn(2,3)

In [9]:
data

array([[-0.35157874,  1.14444642,  1.30526444],
       [-0.56575008,  1.70815363,  0.26100971]])

In [10]:
np.random.randn?

In [11]:
np.random.randint?

In [12]:
data * 10

array([[ -3.51578745,  11.44446418,  13.05264436],
       [ -5.65750079,  17.08153634,   2.61009713]])

In [13]:
data + data 

array([[-0.70315749,  2.28889284,  2.61052887],
       [-1.13150016,  3.41630727,  0.52201943]])

In [14]:
# dimentions

data.shape

(2, 3)

In [15]:
# dtype 

data.dtype

dtype('float64')

### creating ndarry

In [16]:
data1 = [6, 7.5, 8, 1, 3, 9]

In [17]:
arr1 = np.array(data1)

In [18]:
arr1

array([ 6. ,  7.5,  8. ,  1. ,  3. ,  9. ])

In [19]:
data2 = [list(range(4)), list(range(5,9))]

In [20]:
data2

[[0, 1, 2, 3], [5, 6, 7, 8]]

In [21]:
arr2 =np.array(data2)

In [22]:
arr2

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [23]:
# ndim

arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
# creating zeros and ones

np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [27]:
np.zeros((2,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
np.empty((3,5,3))

array([[[  6.91668235e-310,   6.91668235e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310],
        [  6.91665195e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310]],

       [[  6.91665195e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310],
        [  6.91665195e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310]],

       [[  6.91665195e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.91668253e-310],
        [  6.91665195e-310,   6.91668253e-310,   6.91668253e-310],
        [  6.91665195e-310,   6.91668253e-310,   6.91665195e-310],
        [  6.91668253e-310,   6.91665195e-310,   6.9166825

In [32]:
np.zeros?

In [33]:
# arange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# ones

np.ones((10,))

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
_one = list(range(10))

In [36]:
np.ones_like?

In [37]:
np.ones_like(_one)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
np.full?

In [39]:
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [42]:
np.eye?

In [41]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
np.eye(3,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

In [44]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
np.eye(3, k=-1)

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [46]:
np.eye(3, k=-2)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [47]:
np.eye(3, k=-3)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
np.identity?

In [49]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Data	Types	for	ndarrays

In [50]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [51]:
arr2 = np.array([4,5,6], dtype=np.int32)

In [52]:
arr1.dtype

dtype('float64')

In [53]:
arr2.dtype

dtype('int32')

In [54]:
# alter dtype by astype

arr1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [55]:
arr1.astype(np.string_)

array([b'1.0', b'2.0', b'3.0'],
      dtype='|S32')

In [56]:
# 类型转换可以用于整形

arr3 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

In [57]:
arr3.dtype

dtype('float64')

In [59]:
arr3.astype(np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

### Arithmetic	with	NumPy	Arrays

In [60]:
arr = np.array([[1,2,3], [4,5,6]])

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr *  arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [63]:
arr + arr 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [64]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [66]:
arr4 = arr ** 2

In [67]:
arr4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [68]:
arr4 > arr

array([[False,  True,  True],
       [ True,  True,  True]], dtype=bool)

### Basic	Indexing	and	Slicing


In [69]:
arr = np.arange(10)

In [70]:
arr[5]

5

In [71]:
arr[5:8]

array([5, 6, 7])

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
arr[5:8] = 100

In [75]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [76]:
# numpy 的 slice 操作都是基于原 ndarry
# 所以会出现 arr[5:8] 这样的和 python-built-in 不一样的地方
# 这个特性使得 numpy 操作大数据得心应手

In [79]:
# multiple dementional

arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])

In [80]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
old_vals = arr3d[0].copy()

In [83]:
old_vals

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
id(old_vals)

139994594110240

In [85]:
id(arr3d)

139994594107600