## Universal	Functions:	Fast	Element-Wise	Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [7]:
np.exp?

In [9]:
x = np.random.randn(8)

In [10]:
x

array([ 1.0581392 ,  1.81692678,  0.22894661,  1.18183448, -0.48003469,
       -0.23110839,  0.49414363, -0.04592762])

In [11]:
y = np.random.randn(8)

In [12]:
y

array([-1.12270827, -1.03362086,  0.85889465,  1.12808176, -1.09509894,
       -0.14497331, -0.1443335 , -0.65096842])

In [13]:
z = np.random.randn(8)

In [14]:
z

array([ 0.34191349, -0.11688294,  0.27053348,  0.48680962,  0.79033779,
        0.87045306,  0.77348976,  0.60473839])

In [15]:
np.maximum(x,y)

array([ 1.0581392 ,  1.81692678,  0.85889465,  1.18183448, -0.48003469,
       -0.14497331,  0.49414363, -0.04592762])

In [16]:
np.maximum(x,y,z)

array([ 1.0581392 ,  1.81692678,  0.85889465,  1.18183448, -0.48003469,
       -0.14497331,  0.49414363, -0.04592762])

In [17]:
# np.modf

arr = np.random.randn(7) * 5

In [18]:
arr

array([  1.41241496,   9.54848073, -13.72876187,  -7.54746103,
        -3.18341709,  -2.39175905,   2.52202284])

In [19]:
reminder, whole_part = np.modf(arr)

In [20]:
reminder

array([ 0.41241496,  0.54848073, -0.72876187, -0.54746103, -0.18341709,
       -0.39175905,  0.52202284])

In [21]:
whole_part

array([  1.,   9., -13.,  -7.,  -3.,  -2.,   2.])

In [22]:
# handle_exception when computation

arr

array([  1.41241496,   9.54848073, -13.72876187,  -7.54746103,
        -3.18341709,  -2.39175905,   2.52202284])

In [23]:
np.sqrt(arr)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ 1.18845066,  3.09006161,         nan,         nan,         nan,
               nan,  1.58808779])

In [24]:
np.abs(arr)

array([  1.41241496,   9.54848073,  13.72876187,   7.54746103,
         3.18341709,   2.39175905,   2.52202284])

In [25]:
np.fabs(arr)

array([  1.41241496,   9.54848073,  13.72876187,   7.54746103,
         3.18341709,   2.39175905,   2.52202284])

In [26]:
np.fabs?

In [27]:
np.ceil(arr)

array([  2.,  10., -13.,  -7.,  -3.,  -2.,   3.])

In [28]:
np.floor(arr)

array([  1.,   9., -14.,  -8.,  -4.,  -3.,   2.])

In [29]:
np.rint(arr)

array([  1.,  10., -14.,  -8.,  -3.,  -2.,   3.])

In [30]:
np.rint?

In [31]:
arr

array([  1.41241496,   9.54848073, -13.72876187,  -7.54746103,
        -3.18341709,  -2.39175905,   2.52202284])

In [32]:
np.cos(arr)

array([ 0.15772004, -0.99235856,  0.39714608,  0.30174325, -0.99912549,
       -0.73180228, -0.81412834])

In [33]:
np.add?